# cluster_config.yml - cluster configuration
__default__:
    account: sansam-lab
    partition: serial
    time: 16:00:00 # time limit for each job
    cpus-per-task: 2
    mem: 16G
    output: results/logs/slurm-%x.%A.%a.log

fastqc:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

trim_reads_with_trimmomatic:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

trim_reads_with_cutadapt:
    cpus-per-task: 8
    mem: 64G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

align_reads_with_bowtie2:
    cpus-per-task: 12
    mem: 96G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

merge_replicates:
    cpus-per-task: 12
    mem: 96G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

call_peaks_with_sicer:
    time: 02:00:00
    cpus-per-task: 12
    mem: 96G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

call_narrow_peaks_with_macs2:
    cpus-per-task: 2
    mem: 16G
    cores: 12
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

call_broad_peaks_with_macs2:
    cpus-per-task: 2
    mem: 16G
    cores: 2
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bigwigs_no_spikein:
    cpus-per-task: 8
    mem: 16G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_bigwigs_with_spikein:
    cpus-per-task: 8
    mem: 16G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_fingerprint_plots:
    cpus-per-task: 8
    mem: 16G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err

make_fragment_sizes_plots:
    cpus-per-task: 8
    mem: 16G
    cores: 8
    name: "{rule}.{wildcards.sample}"
    output: results/logs/{rule}.{wildcards.sample}.log
    error: results/logs/{rule}.{wildcards.sample}.err
